# Generated by Django 5.2.9 on 2026-03-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='courses/')),
                ('name_courses', models.CharField(max_length=100)),
                ('about_courses', models.CharField(max_length=300)),
            ],
        ),
    ]
