# Generated by Django 5.2.9 on 2026-03-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_app', '0002_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='instructor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='lessons',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='about_courses',
            field=models.TextField(),
        ),
    ]
